### ISSUE TITLE
Support for Rider 2022.3

### ISSUE THREAD

**Issue by SavoInfostream** [GitHubPang/Rossynt#198]
EAP is currently the only way to use .NET 7 in Rider, and since some of my other plugins are working on EAP version 8, is there any chance this plugin could also support EAP?

EDIT: 2022.3 Release is out. Will the support be added soon?

**Comment by PerfectlyFineCode** [comment]
Any updates for this? :)

**Comment by GitHubPang** [comment]
Alright, 2022.3 is supported.
It's back, finally.

Huuuh, life is ________ sometimes 🤷
